BlogApp/config/routes.rb
BlogApp::Application.routes.draw do
  resources :posts do
    
    resources :comments #nested resources
  end 
   resources :categories 
   
  

end

BlogApp/app/models/category.rb
class Category < ActiveRecord::Base
  attr_accessible :name
  
  default_scope :order => "created_at DESC"
  
  validates :name, :presence => true, :length => {:minimum => 5, :maximum => 15}
  
  has_many :posts
  
  def self.default
    find_or_create_by_name("Article")
  end
  
  after_destroy do
    manage_posts
  end
  
  def manage_posts
    posts.each do |post|
      post.update_attribute(:category_id, Category.default.id)
    end
  end
end

BlogApp/app/models/comment.rb
class Comment < ActiveRecord::Base
  attr_accessible :comment, :post_id
  
  default_scope :order => "created_at DESC"
  
  belongs_to :post 
  
  validates :comment, :presence => true
  validates :post_id, :presence => true

end

BlogApp/app/models/post.rb
class Post < ActiveRecord::Base
  attr_accessible :body, :title, :category_id
  
  default_scope :order => "created_at DESC"
  
  belongs_to :category
  
  has_many :comments, :dependent => :destroy
  
  validates :title, :presence => true , :length => {:minimum =>5, :maximum => 50}
  validates :body, :presence =>true
end

BlogApp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery
end

BlogApp/app/controllers/categories_controller.rb
class CategoriesController < ApplicationController
  before_filter :get_post_object, :only =>[:edit, :update,:destroy]

private

  def get_post_object
    @category=Category.find_by_id(params[:id])
    if @category.nil?
      flash[:error]="sorry,no category found!"
      redirect_to categories_path and return
    end
  end

public
  def index
    @categories = Category.all
  end
  
  def new
    @category = Category.new
  end
  
  def edit
  end
  
  def update
    if @category.update_attributes(params[:category])
      flash[:notice]="category has been updated"
      redirect_to categories_path
    else
      render :action =>:edit
    end
  end
  
  def create
    @category= Category.new(params[:category])
    if @category.save
      flash[:notice] = "Category has been successfully created"
      redirect_to categories_path
    else
      render :action =>:new
    end  
  end
  
  def destroy
    if @category == Category.default
      flash[:error] = "sorry, you can not delete the default category"
      redirect_to categories_path
    end  
    @category.destroy
    flash[:notice]="successully deleted the category"
    redirect_to categories_path
  end
end

BlogApp/app/controllers/comments_controller.rb
class CommentsController < ApplicationController
 
 before_filter :get_post
 
  private
 
  def get_post
   @post = Post.find_by_id(params[:post_id])
   if @post.nil?
    flash[:notice] = "sorry, no post found!"
    redirect_to posts_path
   end
  end 

  public
   def index
     @comments=Comment.all
   end
  
  def create
    @comment = @post.comments.build(params[:comment])
    if @comment.save
      flash[:notice] = "comment successfully saved!"
      redirect_to post_path(@post)
    else
      flash[:notice] = "Errors in saving comment"
      redirect_to post_path(@post)
    end
  end
  
  def destroy
    @post = Post.find(params[:post_id])
    @comment = Comment.find(params[:id])
    @comment.destroy
    flash[:notice] = "successully deleted the comment"
    redirect_to post_path(@post)
  end
     
end

BlogApp/app/controllers/posts_controller.rb
class PostsController < ApplicationController

layout "application"

before_filter :get_post_object, :only =>[:show, :edit, :update,:destroy]

private

def get_post_object
    @post=Post.find_by_id(params[:id])
    if @post.nil?
    flash[:notice]="sorry,no post was found!"
    redirect_to posts_path
    end
end

public 


  def index
    @posts=Post.all
  end
  def show
    @comment=Comment.new
  end
  def edit
  end
  def update
  
    if @post.update_attributes(params[:post])
      flash[:notice] = "post has been updated"
      redirect_to post_path(@post)
    else
      render :action =>:edit
    end
  end

  def new
   @post = Post.new
  end

  def create
   @post = Post.new(params[:post])
   if @post.save 
     flash[:notice] = "post has been successfully saved"
     redirect_to posts_path 
   else
    render :action =>:new
   end
 end
  
  def destroy
   
  @post.destroy
  flash[:notice]="successully deleted the post"
  redirect_to posts_path
  end
  
end

BlogApp/app/helpers/application_helper.rb
module ApplicationHelper
  
  def format_date(time)
    time.strftime("%b %d, %Y")
  end 
  
  def render_flash
   ret= ""
   unless flash[:error].blank?
    ret << "<div id='flash_error'>#{flash[:error]}</div>"
   end
   unless flash[:notice].blank?
    ret << "<div id='flash_notice'>#{flash[:notice]}</div>"
   end
   raw(ret)
  end
  
end

BlogApp/app/helpers/categories_helper.rb
module CategoriesHelper
end

BlogApp/app/helpers/comments_helper.rb
module CommentsHelper
end

BlogApp/app/helpers/posts_helper.rb
module PostsHelper
end

BlogApp/app/views/categories/_form.html.erb
<% 
  if @category.new_record?
    url = categories_path
    method = :post
  else
    url = category_path(@category)
    method = :put
  end
%>


<div style="border: 2px solid #efefef; background-color: lightyellow; padding: 10px ">

  <% if @category.errors.any? %>
    <div id="errors" style="color: red">
      <strong>category was not saved because of the following errors</strong>
      <ul>
        <% @category.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @category, :url => url, :method => method  do |f| %>

    Name:
    <br />
    <%= f.text_field :name %> <br />

    
    <%= f.submit "Save this category" %>

  <% end %>

</div>

BlogApp/app/views/categories/edit.html.erb
<h3> Edit the category</h3>

<%= render :partial => "form" %>

BlogApp/app/views/categories/index.html.erb
<h1>Category</h1>
<%= link_to "Create New category", new_category_path %>
<hr/>

<% @categories.each do |category| %>

<div style="padding:10px; margin: 10px; background-color: #efefef; border: 2px solid #aaa">

<strong><%= link_to category.name , category_path(category) %></br></strong>
<br />
<small> Published on: <%= format_date(category.created_at) %></small> <br />
<%= link_to "Delete category",category_path(category),:method=>:delete,:data=>{:confirm=> "Are you sure"}%>
<%= link_to "edit this", edit_category_path(category)%>
</div>
<% end %>

BlogApp/app/views/categories/new.html.erb
<h2>Categories</h2>
<hr />
<h3>create new category</h3>
<%= render :partial => "form" %>

BlogApp/app/views/comments/_comments.html.erb
<% if @post.comments.empty? %>
  No comments found!
  <% else %>
    <% @post.comments.each do |comment| %>
  <div style="padding: 10px; margin: 10px; background: lightgreen; border: 2px  solid green">
  <%= simple_format(comment.comment) %>
  <br />
  <small>Comment posted on: <%= format_date(comment.created_at) %></small>
  <%= link_to "Delete comment",post_comment_path(@post,comment),:confirm=> 'Are you sure?',:method=> :delete %>
  </div>
  <% end %>
<%end %>

BlogApp/app/views/comments/_form.html.erb
<div id="new_comment" style="display: none; background-color: lightyellow; padding: 10px; margin: 10px; border: 2px solid yellow;">
  <strong>Add New Comment</strong>

  <%= form_for @comment, :url => post_comments_path(@post) do |f| %>

    Comment:
    <br />
    <%= f.text_area :comment %>

    <br />
    <%= f.submit "Save this Comment" %> or <%= link_to_function "Cancel", "$('#new_comment').hide()" %>
  <% end %>
</div>

BlogApp/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>BlogApp</title>
  <%= stylesheet_link_tag "application" %>
  <%= javascript_include_tag "application" %>
  <%= csrf_meta_tags %>
</head>
<body>
<div id="main">
  <div id="wrapper">
    <%= render :partial => "shared/header" %>
      <div id="flash">
        <%= render_flash %>
      </div>
      <div id="content">
        <%= yield %>
      </div>
     <%= render :partial => "shared/footer" %>
  </div>
</div>
     
</body>
</html>

BlogApp/app/views/posts/_form.html.erb
<%
  if @post.new_record?
    url = posts_path
    method = :post
  else
    url = post_path(@post)
    method = :put
  end
%>


<div style="border: 2px solid #efefef; background-color: lightyellow; padding: 10px ">

  <% if @post.errors.any? %>
    <div id="errors" style="color: red">
      <strong>Post was not saved because of the following errors</strong>
      <ul>
        <% @post.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <%= form_for @post, :url => url, :method => method  do |f| %>

    Category: <%= f.select :category_id, Category.all.collect{|c| [c.name, c.id]} %>
    <br/>
    
    Title:
    <br />
    <%= f.text_field :title %> <br />

    Body:
    <br />
    <%= f.text_area :body %> <br />


    <%= f.submit "Save this Post" %>

  <% end %>

</div>

BlogApp/app/views/posts/edit.html.erb
<%= link_to "View All Posts", posts_path %> | <%= link_to "Back to the post", post_path(@post) %>
<h3> Edit Post</h3>
<%= render :partial => "form" %>

BlogApp/app/views/posts/index.html.erb
<h1>Post</h1>
<%= link_to "Create New Post", new_post_path %>
<hr/>

<% @posts.each do |post| %>

  <div style="padding:10px; margin: 10px; background-color: #efefef; border: 2px solid #aaa">

    <strong><%= link_to post.title , post_path(post) %></br></strong>
    
    <br />
    
    <%= post.category.name %>
 <br />   

    
    <small> Published on: <%= format_date(post.created_at) %></small> <br />
    
    <%= link_to "Delete post",post_path(post), :method => :delete, :data=> {:confirm => "Are you sure?"} %>
  </div>
<% end %>

BlogApp/app/views/posts/new.html.erb
<h2>Posts</h2>
<%= link_to "View All Posts", posts_path %>
<hr />
<h3>create new post</h3>

<%= render :partial => "form" %>

BlogApp/app/views/posts/show.html.erb
<%=link_to "viewing all posts" ,posts_path %>


<div style="padding: 10px; margin: 10px; background-color:#efefef; border: 2px solid #aaa">
  <strong><%=@post.title%></strong><br/>
  <%= simple_format(@post.body)%><br/>

  <small>published on:<%= format_date(@post.created_at)%></small>
</div>

<%= link_to "edit this", edit_post_path(@post)%>
<%= link_to "Delete post", post_path(@post), :method=>:delete, :data=>{:confirm=> "Are you sure?"} %>
<%= link_to_function "Add comment", "$('#new_comment').show()" %>

<h3>Comments</h3>
 <%= render :partial => "comments/form" %>
 <%= render :partial => "comments/comments" %>

BlogApp/app/views/shared/_footer.html.erb
<div id="footer">
  <center>
    The BlogApp. copyright &copy; <%= Time.now.year %>. All rights reserved
   </center>
</div>   
   

BlogApp/app/views/shared/_header.html.erb
<div id="header">
  <h2> The BlogAPP<?h2>
  
  <div id="nav">
    <%= link_to "posts", posts_path, :class => (params[:controller]=="posts" ? "active" : "") %>|<%= link_to "categories", categories_path, :class => (params[:controller]=="categories" ? "active" : "") %>
  </div>
</div>   